language: python
python:
- 2.7
sudo: false
cache:
  timeout: 3600
  pip: true
  directory:
  - ${HOME}/google_appengine
  - ${HOME}/google-cloud-sdk
env:
- CLOUDSDK_CORE_DISABLE_PROMPTS=1 GAE_PYTHONPATH=${HOME}/google_appengine GCSDK_PATH=${HOME}/google-cloud-sdk
  PATH=${GAE_PYTHONPATH}:${GAE_PYTHONPATH}/lib/:${GAE_PYTHONPATH}/lib/yaml/lib/:$PATH:${HOME}/google-cloud-sdk/bin
before_install:
- openssl aes-256-cbc -K $encrypted_5401ef4ab636_key -iv $encrypted_5401ef4ab636_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- cd ../../..
- if [ ! -d "$GAE_PYTHONPATH" ]; then wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.38.zip;
  unzip -q google_appengine_1.9.38.zip; fi
- if [ ! -d "$GCSDK_PATH" ]; then curl https://sdk.cloud.google.com | bash; fi
- cd build/simpeg/website
install:
- pip install -r requirements.txt
script:
- make build
after_success:
- ./deploy.sh
